# Generated by Django 3.1.1 on 2020-09-10 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_cancha', models.CharField(blank=True, choices=[('C07', 'Cancha de 7'), ('C11', 'Cancha de 11')], default='', max_length=3)),
                ('tiene_vestuario', models.BooleanField(default=False)),
                ('tiene_iluminacion', models.BooleanField(default=False)),
                ('tiene_cesped_sintetico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=120)),
                ('empleado', models.CharField(max_length=120)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_reserva', models.DateTimeField()),
            ],
        ),
    ]
