# Generated by Django 3.1.1 on 2020-09-10 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=120)),
                ('employee', models.CharField(max_length=120)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('booked_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('field_type', models.CharField(blank=True, choices=[('C05', 'Cancha de 5'), ('C07', 'Cancha de 7'), ('C11', 'Cancha de 11')], default='', max_length=3)),
                ('has_locker', models.BooleanField(default=False)),
                ('has_light', models.BooleanField(default=False)),
                ('has_synthetic_grass', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Cancha',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.AddField(
            model_name='booking',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_field', to='reservas.field'),
        ),
    ]
